#################
# Sflow Filters #
#################

filter {

    if [type] == "sflow" {

# sFlow sends two kinds of messages - CNTRs and FLOWs
# I'm not doing anything with CNTRs at this point, so
# I drop those, and we concentrate on processing FLOW
# messages.

        if [message] =~ /CNTR/ {
            drop { }
        }

# sFlow FLOW messages break down into the following fields.
# I have named them arbitrarily, but they correspond to the
# actual field names.  I developed this grok pattern using 
# two tools:
#
# - sflowtool (http://www.inmon.com/technology/sflowTools.php)
#   Written by InMon, it provides a way to examine sFlow messages
#   in human readable format.
#
# - Grok Debugger (https://grokdebug.herokuapp.com/)
#   Invaluable, and self-explanatory.

        grok {
            match => { "message" => "%{WORD:SampleType},%{IP:sflow_ReporterIP},%{NUMBER:sflow_inputPort},%{NUMBER:sflow_outputPort},%{WORD:sflow_srcMAC},%{WORD:sflow_dstMAC},%{DATA:sflow_EtherType2},%{NUMBER:sflow_in_vlan},%{NUMBER:sflow_out_vlan},%{IP:sflow_srcIP},%{IP:sflow_dstIP},%{NUMBER:sflow_IPProtocol},%{WORD:sflow_IPTOS2},%{NUMBER:sflow_IPTTL},%{NUMBER:sflow_srcPort},%{NUMBER:sflow_dstPort},%{WORD:sflow_tcpFlags},%{NUMBER:sflow_PacketSize},%{NUMBER:sflow_IPSize},%{NUMBER:sflow_SampleRate}" }
        }

# Sometimes it doesn't work out.

        if "_grokparsefailure" in [tags] {
            drop { }
        }


# I also want to translate things like Source and
# Destination port numbers into known service names.
# for this to work, you have to built some YAML files,
# which basically map everything you'd find in an
# /etc/services file.  I'll post my YAML files in
# other Gists.

        translate {
            field => "[sflow_srcPort]"
            destination => "[sflow_SrcSvcName]"
            dictionary_path => "/etc/logstash/dictionaries/iana_services.yaml"
        }

        translate {
            field => "[sflow_dstPort]"
            destination => "[sflow_DstSvcName]"
            dictionary_path => "/etc/logstash/dictionaries/iana_services.yaml"
        }

        translate {
            field => "[sflow_IPProtocol]"
            destination => "[sflow_IP_Protocol]"
            dictionary_path => "/etc/logstash/dictionaries/iana_protocols.yaml"
        }

        translate {
            field => "[sflow_tcpFlags]"
            destination => "[sflow_TCPFlagDecode]"
            dictionary_path => "/etc/logstash/dictionaries/tcp_flags.yaml"
        }
	translate {
	    field => "sflow_EtherType2"
	    destination => "[sflow_EtherType]"
	    dictionary_path => "/etc/logstash/dictionaries/ieee_ethertype.yaml"
	}
        translate {
            field => "sflow_IPTOS2"
            destination => "[sflow_IPToS]"
            dictionary_path => "/etc/logstash/dictionaries/rfc_tos.yaml"
        }


# There are a bunch of fields from the original
# message, as well as some I created temporarily,
# that I don't care to store.  Here's where I drop
# them all.

        mutate {
            remove_field => [ "host", "command", "sflow_IPTOS2", "sflow_EtherType2", "sflow_IPProtocol", "sflow_inputPort", "sflow_outputPort", "sflow_tcpFlags", "message", "src_host", "dst_host", "rep_host", "SampleType", "domain" ]
        }


# Lastly, we're going to want Kibana and
# Elasticsearch to be able to do some math
# with certain fields, so make sure they're
# handled as numbers, rather than strings.
# You can also do this by setting up templates
# in Elasticsearch, but this is easier.

        mutate {
                convert => {
                        "sflow_PacketSize" => "integer"
                        "sflow_SampleRate" => "integer"
                }
        }

    }

}
