output {
    if [type] == "sflow" {
    elasticsearch {
        hosts => ["localhost:9200"]
        action => "index"
        index => "sflow-%{+YYYY.MM.dd}"
#	template_overwrite => true
    }
    stdout {}
}
}
